import time
import random
from core import BaseRiddle, riddle, _salted_hash

def _make_sequence_trap(rng):
    start = rng.randint(1000, 9999)

    def look_say(n):
        s, result = str(n), ''
        i = 0

        while i < len(s):
            ch, count = s[i], 1

            while i + count < len(s) and s[i + count] == ch:
                count += 1

            result += str(count) + ch
            i += count

        return int(result)

    chain = [start]

    for _ in range(4):
        chain.append(look_say(chain[-1]))

    answer = str(chain[4])
    decoys = [str(chain[4] + rng.randint(-99, 99)) for _ in range(3)]

    rng.shuffle(decoys)

    labels = ['A', 'B', 'C', 'D']
    slot = rng.randint(0, 3)
    options = decoys[:]
    options.insert(slot, answer)
    analyst_lines = '\n'.join(
        f'  Analyst {labels[i]}: {options[i]}' for i in range(4)
    )

    stem = (
        f'Observe this sequence generated by a strict rule:\n'
        f'\n'
        f'  Term 1: {chain[0]}\n'
        f'  Term 2: {chain[1]}\n'
        f'  Term 3: {chain[2]}\n'
        f'  Term 4: {chain[3]}\n'
        f'\n'
        f'Rule: each term describes the PREVIOUS term by counting\n'
        f'consecutive runs of identical digits, left to right.\n'
        f'Example: 3344 → one run of two 3s, one run of two 4s → 2324\n'
        f'\n'
        f'Four analysts independently computed Term 5:\n'
        f'{analyst_lines}\n'
        f'\n'
        f'Exactly one is correct.  What is Term 5?\n'
        f'Answer with the number only.'
    )

    return stem, answer

def _make_modular_trap(rng):
    a = rng.randint(17, 97)
    b = rng.randint(3, 11)
    c = rng.randint(2, 9)

    s1 = a * b
    s2 = s1 + 1
    s3 = s2 % (c * 2)
    s4 = s3 + 3
    s5 = s4 * c - 4

    answer = str(s5)

    stem = (
        f'Execute this procedure exactly, tracking R:\n'
        f'\n'
        f'  Step 1: R = {a} × {b}\n'
        f'  Step 2: R = R + (number of steps fully completed before this one)\n'
        f'  Step 3: R = R mod ({c} × steps fully completed before this one)\n'
        f'  Step 4: R = R + (number of steps fully completed before this one)\n'
        f'  Step 5: R = (R × {c}) − (number of steps fully completed before this one)\n'
        f'\n'
        f'"Steps fully completed before step N" = N − 1.\n'
        f'Show no working — give only the final value of R.\n'
        f'Answer with the number only.'
    )

    return stem, answer

def _make_index_trap(rng):
    filler = ['alpha', 'beta', 'gamma', 'delta', 'epsilon',
              'zeta',  'eta',  'theta', 'iota',  'kappa',
              'mu',    'nu',   'xi',    'rho',   'sigma']
    k = rng.randint(3, 6)
    chosen = rng.sample(filler, k)
    base = ' '.join(chosen)

    n = 5 + k

    for _ in range(10):
        candidate = f'This sentence contains {n} words: {base}.'
        actual = len(candidate.split())

        if actual == n:
            break

        n = actual

    answer = str(n)
    wrong = str(n + rng.choice([-2, -1, 1, 2]))

    stem = (
        f'Read this sentence carefully:\n'
        f'\n'
        f'  "This sentence contains {n} words: {base}."\n'
        f'\n'
        f'A student claims the stated count is wrong and the real count is {wrong}.\n'
        f'The sentence itself claims the count is {n}.\n'
        f'\n'
        f'Count every space-separated token in the sentence above.\n'
        f'The trailing period is part of the last word, not a separate token.\n'
        f'The number {n} counts as one token.\n'
        f'\n'
        f'What is the correct word count?  Answer with the number only.'
    )

    return stem, answer


_GENERATORS = [_make_sequence_trap, _make_modular_trap, _make_index_trap]


@riddle('paradox')
class ParadoxRiddle(BaseRiddle):
    def generate(self):
        self._deadline = 120

        rng = random.Random(self._seed)
        gen = rng.choice(_GENERATORS)
        stem, answer = gen(rng)

        self._lock(answer)

        noise = hex(hash(str(int(time.time()) // 300) + self._seed) & 0xFFFF)[2:]

        lines = stem.split('\n')
        text = '\n'.join([
            f'┌─ PARADOX ENGINE ─[{noise}]──────────────────────────────────────┐',
            *[f'│  {l}' for l in lines],
            '│',
            f'│  ⏱  {self._deadline}s.  Answer: single integer, nothing else.',
            '└────────────────────────────────────────────────────────────────────┘'
        ])

        return {'text': text, 'type': 'paradox', 'metadata': {'noise': noise}}

    def validate(self, answer):
        result = super().validate(answer)

        if not result['ok']:
            cleaned = answer.strip().rstrip('.')

            if _salted_hash(cleaned, self._salt) == self._answer_hash:
                result['ok'] = True

        return result

    def hint(self, attempt_n):
        return [
            'Ignore the framing entirely — execute the math step by step.',
            'Write every intermediate value on paper before committing.',
            'Re-read what "steps completed before this one" means for each step.'
        ][min(attempt_n, 2)]
